import type { ISOClause, SchoolSubmission } from "@/components/iso/types"

export const mockClauses: ISOClause[] = [
  {
    id: "clause-001",
    number: "4.1",
    title: "Understanding the organization and its context",
    description:
      "The organization shall determine external and internal issues that are relevant to its purpose and its strategic direction and that affect its ability to achieve the intended result(s) of its EOMS.",
    requirements: [
      "Determine external and internal issues relevant to the organization's purpose and strategic direction",
      "Monitor and review information about these external and internal issues",
      "Document how these issues affect the organization's ability to achieve intended results",
    ],
    status: "approved",
    lastUpdated: "2023-05-10T14:30:00Z",
    submittedBy: "Sarah Williams",
    submittedAt: "2023-05-08T10:15:00Z",
    reviewedBy: "Alex Johnson",
    reviewedAt: "2023-05-10T14:30:00Z",
    comments: "All requirements have been met. Documentation is comprehensive and well-organized.",
    documents: [
      {
        id: "doc-1",
        name: "Context Analysis Report.pdf",
        fileUrl: "#",
        fileType: "application/pdf",
        uploadedBy: "Sarah Williams",
        uploadedAt: "2023-05-08T10:15:00Z",
        size: "2.4 MB",
      },
      {
        id: "doc-2",
        name: "Strategic Direction Document.docx",
        fileUrl: "#",
        fileType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        uploadedBy: "Sarah Williams",
        uploadedAt: "2023-05-08T10:15:00Z",
        size: "1.8 MB",
      },
    ],
    guidelines: [
      {
        id: "guide-1",
        name: "Context Analysis Guidelines.pdf",
        fileUrl: "#",
        fileType: "application/pdf",
        uploadedBy: "Admin",
        uploadedAt: "2023-01-15T08:00:00Z",
        size: "1.2 MB",
      },
    ],
  },
  {
    id: "clause-002",
    number: "4.2",
    title: "Understanding the needs and expectations of interested parties",
    description:
      "The organization shall determine the interested parties that are relevant to the EOMS, and the requirements of these interested parties.",
    requirements: [
      "Identify all interested parties relevant to the educational organization",
      "Determine the requirements of these interested parties",
      "Monitor and review information about these interested parties and their relevant requirements",
    ],
    status: "submitted",
    lastUpdated: "2023-05-12T09:45:00Z",
    submittedBy: "Sarah Williams",
    submittedAt: "2023-05-12T09:45:00Z",
    documents: [
      {
        id: "doc-3",
        name: "Stakeholder Analysis.xlsx",
        fileUrl: "#",
        fileType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        uploadedBy: "Sarah Williams",
        uploadedAt: "2023-05-12T09:45:00Z",
        size: "1.2 MB",
      },
    ],
    guidelines: [],
  },
  {
    id: "clause-003",
    number: "4.3",
    title: "Determining the scope of the management system for educational organizations",
    description:
      "The organization shall determine the boundaries and applicability of the EOMS to establish its scope.",
    requirements: [
      "Define the boundaries and applicability of the EOMS",
      "Consider external and internal issues referred to in 4.1",
      "Consider the requirements of relevant interested parties referred to in 4.2",
      "Consider the products and services of the organization",
    ],
    status: "rejected",
    lastUpdated: "2023-05-05T16:20:00Z",
    submittedBy: "Sarah Williams",
    submittedAt: "2023-05-03T11:30:00Z",
    reviewedBy: "Alex Johnson",
    reviewedAt: "2023-05-05T16:20:00Z",
    comments:
      "The scope definition is incomplete. Please include all educational services provided by the organization and clarify the boundaries of the management system.",
    documents: [
      {
        id: "doc-4",
        name: "EOMS Scope Document.pdf",
        fileUrl: "#",
        fileType: "application/pdf",
        uploadedBy: "Sarah Williams",
        uploadedAt: "2023-05-03T11:30:00Z",
        size: "980 KB",
      },
    ],
    guidelines: [],
  },
  {
    id: "clause-004",
    number: "4.4",
    title: "Management system for educational organizations (EOMS)",
    description:
      "The organization shall establish, implement, maintain and continually improve an EOMS, including the processes needed and their interactions, in accordance with the requirements of this document.",
    requirements: [
      "Establish processes needed for the EOMS and their interactions",
      "Implement and maintain these processes",
      "Continually improve the EOMS",
      "Determine criteria and methods for effective operation and control",
    ],
    status: "pending",
    lastUpdated: "2023-04-15T08:00:00Z",
    guidelines: [],
  },
  {
    id: "clause-005",
    number: "5.1",
    title: "Leadership and commitment",
    description: "Top management shall demonstrate leadership and commitment with respect to the EOMS.",
    requirements: [
      "Take accountability for the effectiveness of the EOMS",
      "Ensure the EOMS policy and objectives are established and compatible with the context and strategic direction",
      "Ensure integration of the EOMS requirements into the organization's business processes",
      "Promote the use of the process approach and risk-based thinking",
    ],
    status: "pending",
    lastUpdated: "2023-04-15T08:00:00Z",
    guidelines: [],
  },
  {
    id: "clause-006",
    number: "5.2",
    title: "Policy",
    description: "Top management shall establish, review and maintain an educational policy.",
    requirements: [
      "Establish an educational policy appropriate to the purpose of the organization",
      "Provide a framework for setting educational objectives",
      "Include a commitment to satisfy applicable requirements",
      "Include a commitment to continual improvement of the EOMS",
    ],
    status: "pending",
    lastUpdated: "2023-04-15T08:00:00Z",
    guidelines: [],
  },
  {
    id: "clause-007",
    number: "6.1",
    title: "Actions to address risks and opportunities",
    description:
      "The organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed.",
    requirements: [
      "Determine risks and opportunities that need to be addressed",
      "Plan actions to address these risks and opportunities",
      "Integrate and implement the actions into EOMS processes",
      "Evaluate the effectiveness of these actions",
    ],
    status: "pending",
    lastUpdated: "2023-04-15T08:00:00Z",
    guidelines: [],
  },
  {
    id: "clause-008",
    number: "7.1",
    title: "Resources",
    description:
      "The organization shall determine and provide the resources needed for the establishment, implementation, maintenance and continual improvement of the EOMS.",
    requirements: [
      "Determine and provide necessary resources for the EOMS",
      "Consider the capabilities of, and constraints on, existing internal resources",
      "Determine what needs to be obtained from external providers",
    ],
    status: "pending",
    lastUpdated: "2023-04-15T08:00:00Z",
    guidelines: [],
  },
]

export const mockSchoolSubmissions: SchoolSubmission[] = [
  {
    id: "sub-001",
    schoolId: "school-001",
    schoolName: "Greenwood Elementary",
    clauseId: "clause-001",
    clauseNumber: "4.1",
    clauseTitle: "Understanding the Organization and its Context",
    documentCount: 3,
    submittedBy: "Sarah Johnson",
    submittedAt: "2024-01-15T10:30:00Z",
    status: "submitted",
  },
  {
    id: "sub-002",
    schoolId: "school-002",
    schoolName: "Riverside High School",
    clauseId: "clause-002",
    clauseNumber: "4.2",
    clauseTitle: "Understanding the Needs and Expectations of Interested Parties",
    documentCount: 2,
    submittedBy: "Michael Chen",
    submittedAt: "2024-01-14T14:20:00Z",
    status: "approved",
    reviewedBy: "Alex Johnson",
    reviewedAt: "2024-01-16T09:15:00Z",
    comments: "All requirements met. Well documented processes.",
  },
  {
    id: "sub-003",
    schoolId: "school-003",
    schoolName: "Oakwood Academy",
    clauseId: "clause-003",
    clauseNumber: "5.1",
    clauseTitle: "Leadership and Commitment",
    documentCount: 4,
    submittedBy: "Emily Davis",
    submittedAt: "2024-01-13T16:45:00Z",
    status: "rejected",
    reviewedBy: "Alex Johnson",
    reviewedAt: "2024-01-15T11:30:00Z",
    comments:
      "Missing leadership commitment documentation. Please provide signed policy statements and evidence of leadership involvement in quality management.",
  },
  {
    id: "sub-004",
    schoolId: "school-001",
    schoolName: "Greenwood Elementary",
    clauseId: "clause-004",
    clauseNumber: "5.2",
    clauseTitle: "Policy",
    documentCount: 2,
    submittedBy: "Sarah Johnson",
    submittedAt: "2024-01-12T13:10:00Z",
    status: "submitted",
  },
  {
    id: "sub-005",
    schoolId: "school-004",
    schoolName: "Maple Valley School",
    clauseId: "clause-005",
    clauseNumber: "6.1",
    clauseTitle: "Actions to Address Risks and Opportunities",
    documentCount: 5,
    submittedBy: "David Wilson",
    submittedAt: "2024-01-11T08:25:00Z",
    status: "approved",
    reviewedBy: "Alex Johnson",
    reviewedAt: "2024-01-14T15:45:00Z",
    comments: "Comprehensive risk assessment and mitigation strategies provided.",
  },
]

export const mockSchoolsProgress = [
  {
    id: "school-001",
    name: "Greenwood Elementary",
    logo: "/placeholder.svg?height=40&width=40",
    primaryColor: "#10B981",
    secondaryColor: "#059669",
    totalClauses: 24,
    pendingClauses: 8,
    submittedClauses: 4,
    approvedClauses: 12,
    rejectedClauses: 0,
    progress: 50,
    isCertified: false,
    lastUpdated: "2024-01-15T10:30:00Z",
  },
  {
    id: "school-002",
    name: "Riverside High School",
    logo: "/placeholder.svg?height=40&width=40",
    primaryColor: "#3B82F6",
    secondaryColor: "#2563EB",
    totalClauses: 24,
    pendingClauses: 0,
    submittedClauses: 0,
    approvedClauses: 24,
    rejectedClauses: 0,
    progress: 100,
    isCertified: true,
    lastUpdated: "2024-01-16T09:15:00Z",
  },
  {
    id: "school-003",
    name: "Oakwood Academy",
    logo: "/placeholder.svg?height=40&width=40",
    primaryColor: "#F59E0B",
    secondaryColor: "#D97706",
    totalClauses: 24,
    pendingClauses: 15,
    submittedClauses: 2,
    approvedClauses: 6,
    rejectedClauses: 1,
    progress: 25,
    isCertified: false,
    lastUpdated: "2024-01-13T16:45:00Z",
  },
  {
    id: "school-004",
    name: "Maple Valley School",
    logo: "/placeholder.svg?height=40&width=40",
    primaryColor: "#8B5CF6",
    secondaryColor: "#7C3AED",
    totalClauses: 24,
    pendingClauses: 6,
    submittedClauses: 1,
    approvedClauses: 17,
    rejectedClauses: 0,
    progress: 71,
    isCertified: false,
    lastUpdated: "2024-01-11T08:25:00Z",
  },
  {
    id: "school-005",
    name: "Sunset Middle School",
    logo: "/placeholder.svg?height=40&width=40",
    primaryColor: "#EF4444",
    secondaryColor: "#DC2626",
    totalClauses: 24,
    pendingClauses: 0,
    submittedClauses: 0,
    approvedClauses: 24,
    rejectedClauses: 0,
    progress: 100,
    isCertified: true,
    lastUpdated: "2024-01-10T14:20:00Z",
  },
]
