import type { Student } from "./types"

export const mockStudents: Student[] = [
  {
    id: "1",
    name: "Aarav Sharma",
    photo: "/placeholder.svg?height=40&width=40&text=AS",
    gender: "Male",
    dateOfBirth: "2010-05-15",
    rollNumber: "G5A001",
    class: "5",
    section: "A",
    guardianName: "Rajesh Sharma",
    parentContact: "9876543210",
    address: "123 Main Street, Kathmandu",
  },
  {
    id: "2",
    name: "Priya Patel",
    photo: "/placeholder.svg?height=40&width=40&text=PP",
    gender: "Female",
    dateOfBirth: "2010-08-22",
    rollNumber: "G5A002",
    class: "5",
    section: "A",
    guardianName: "Amit Patel",
    parentContact: "9876543211",
    address: "456 Oak Avenue, Kathmandu",
  },
  {
    id: "3",
    name: "Rohan Singh",
    photo: "/placeholder.svg?height=40&width=40&text=RS",
    gender: "Male",
    dateOfBirth: "2010-03-10",
    rollNumber: "G5A003",
    class: "5",
    section: "A",
    guardianName: "Vikram Singh",
    parentContact: "9876543212",
    address: "789 Pine Road, Kathmandu",
  },
  {
    id: "4",
    name: "Ananya Gupta",
    photo: "/placeholder.svg?height=40&width=40&text=AG",
    gender: "Female",
    dateOfBirth: "2010-11-05",
    rollNumber: "G5B001",
    class: "5",
    section: "B",
    guardianName: "Rahul Gupta",
    parentContact: "9876543213",
    address: "101 Cedar Lane, Kathmandu",
  },
  {
    id: "5",
    name: "Arjun Kumar",
    photo: "/placeholder.svg?height=40&width=40&text=AK",
    gender: "Male",
    dateOfBirth: "2010-07-18",
    rollNumber: "G5B002",
    class: "5",
    section: "B",
    guardianName: "Sanjay Kumar",
    parentContact: "9876543214",
    address: "202 Maple Street, Kathmandu",
  },
  {
    id: "6",
    name: "Neha Joshi",
    photo: "/placeholder.svg?height=40&width=40&text=NJ",
    gender: "Female",
    dateOfBirth: "2010-01-30",
    rollNumber: "G5B003",
    class: "5",
    section: "B",
    guardianName: "Prakash Joshi",
    parentContact: "9876543215",
    address: "303 Birch Road, Kathmandu",
  },
  {
    id: "7",
    name: "Vihaan Mehta",
    photo: "/placeholder.svg?height=40&width=40&text=VM",
    gender: "Male",
    dateOfBirth: "2011-04-12",
    rollNumber: "G4A001",
    class: "4",
    section: "A",
    guardianName: "Nikhil Mehta",
    parentContact: "9876543216",
    address: "404 Elm Street, Kathmandu",
  },
  {
    id: "8",
    name: "Ishita Verma",
    photo: "/placeholder.svg?height=40&width=40&text=IV",
    gender: "Female",
    dateOfBirth: "2011-09-25",
    rollNumber: "G4A002",
    class: "4",
    section: "A",
    guardianName: "Deepak Verma",
    parentContact: "9876543217",
    address: "505 Walnut Avenue, Kathmandu",
  },
  {
    id: "9",
    name: "Aditya Thapa",
    photo: "/placeholder.svg?height=40&width=40&text=AT",
    gender: "Male",
    dateOfBirth: "2011-06-08",
    rollNumber: "G4A003",
    class: "4",
    section: "A",
    guardianName: "Sunil Thapa",
    parentContact: "9876543218",
    address: "606 Spruce Lane, Kathmandu",
  },
  {
    id: "10",
    name: "Kavya Shrestha",
    photo: "/placeholder.svg?height=40&width=40&text=KS",
    gender: "Female",
    dateOfBirth: "2011-12-15",
    rollNumber: "G4B001",
    class: "4",
    section: "B",
    guardianName: "Ramesh Shrestha",
    parentContact: "9876543219",
    address: "707 Fir Road, Kathmandu",
  },
]
