import type { Training } from "./types"

export const mockTrainings: Training[] = [
  {
    id: "1",
    title: "ISO 21001 Implementation Workshop",
    description: "Learn how to implement ISO 21001 standards in your educational institution effectively.",
    date: "2025-05-20",
    time: "10:00 AM - 2:00 PM",
    trainer: "Dr. Sarah Johnson",
    category: "ISO Standards",
    materials: [
      { name: "Slides", url: "/materials/iso-slides.pdf" },
      { name: "Workbook", url: "/materials/iso-workbook.pdf" },
    ],
    registeredUsers: [],
  },
  {
    id: "2",
    title: "Digital Learning Tools for Educators",
    description: "Explore the latest digital tools and technologies to enhance classroom learning experiences.",
    date: "2025-05-25",
    time: "9:00 AM - 12:00 PM",
    trainer: "Prof. Michael Chen",
    category: "EdTech",
    materials: [
      { name: "Tool Guide", url: "/materials/digital-tools-guide.pdf" },
      { name: "Practice Files", url: "/materials/practice-files.zip" },
    ],
    registeredUsers: ["current-user-id"],
  },
  {
    id: "3",
    title: "Student Assessment Strategies",
    description: "Discover effective assessment methods to evaluate student learning and provide meaningful feedback.",
    date: "2025-06-05",
    time: "1:00 PM - 4:00 PM",
    trainer: "Dr. Emily Rodriguez",
    category: "Pedagogy",
    materials: [{ name: "Assessment Guide", url: "/materials/assessment-guide.pdf" }],
    registeredUsers: [],
  },
  {
    id: "4",
    title: "Inclusive Education Practices",
    description: "Learn strategies to create inclusive learning environments that support diverse student needs.",
    date: "2025-06-12",
    time: "10:00 AM - 3:00 PM",
    trainer: "Dr. James Wilson",
    category: "Inclusion",
    materials: [
      { name: "Handbook", url: "/materials/inclusive-handbook.pdf" },
      { name: "Case Studies", url: "/materials/case-studies.pdf" },
    ],
    registeredUsers: [],
  },
  {
    id: "5",
    title: "School Leadership Development",
    description: "Develop essential leadership skills for effective school management and educational leadership.",
    date: "2025-06-18",
    time: "9:00 AM - 5:00 PM",
    trainer: "Prof. Lisa Thompson",
    category: "Leadership",
    materials: [{ name: "Leadership Guide", url: "/materials/leadership-guide.pdf" }],
    registeredUsers: [],
  },
  {
    id: "6",
    title: "Data-Driven Decision Making in Education",
    description: "Learn how to collect, analyze, and use data to inform educational decisions and improve outcomes.",
    date: "2025-06-25",
    time: "1:00 PM - 4:00 PM",
    trainer: "Dr. Robert Kim",
    category: "Data Analytics",
    materials: [
      { name: "Data Toolkit", url: "/materials/data-toolkit.pdf" },
      { name: "Excel Templates", url: "/materials/excel-templates.xlsx" },
    ],
    registeredUsers: [],
  },
]
